### ISSUE TITLE
functional components

### ISSUE THREAD

**Issue by ghost** [luisrudge/react-transform-sentry#4]
For my project, it is not catching errors that happen in functional components. Did I not configure it correctly?

**Comment by luisrudge** [comment]
I don't think it works with function components because we have to monkey patch the methods: https://github.com/luisrudge/react-transform-sentry/blob/master/src/index.js#L9

In any case, you should be using react@16 with error boundaries: https://blog.sentry.io/2017/09/28/react-16-error-boundaries
it's amazing!
